services:
  - type: web
    name: apk-detector
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    region: oregon
    envVars:
      - key: NODE_VERSION
        value: 18
